# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "56228cbd74ca786fc36978f7774728d4"
application_url = "https://paste-roses-loved-sie.trycloudflare.com"
embedded = true
name = "Abundance"
handle = "abundance"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://paste-roses-loved-sie.trycloudflare.com/auth/callback",
  "https://paste-roses-loved-sie.trycloudflare.com/auth/shopify/callback",
  "https://paste-roses-loved-sie.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "abundance-together.myshopify.com"
automatically_update_urls_on_dev = true
